# Generated by Django 4.0.4 on 2022-05-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto_Curr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('symbol', models.CharField(max_length=12)),
                ('avg_price', models.FloatField()),
                ('binance_price', models.FloatField()),
                ('binance_maxPrice', models.FloatField()),
                ('FTX_price', models.FloatField()),
                ('FTX_maxPrice', models.FloatField()),
                ('Kraken_price', models.FloatField()),
                ('Kraken_maxPrice', models.FloatField()),
                ('GateIo_price', models.FloatField()),
                ('GateIo_maxPrice', models.FloatField()),
            ],
        ),
    ]
