# Generated by Django 4.0.4 on 2022-05-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto_curr',
            name='avg_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
